###################
# dev
###################

server.port: 18080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hanexdb
    driverClassName: org.postgresql.Driver
    username: hanex
    password: hanex1234
  redis:
    host: localhost
    port: 6001

logging:
  config: classpath:log4j2-dev.xml

