spring:
  application:
    name: starter
  profiles:
    active: local2
  lifecycle:
    timeout-per-shutdown-phase: 10s # graceful shutdown 유예시간 설정

# cache ttl 설정 (cacheName:ttl)
custom:
  cache:

#--------------------------
# logging
#--------------------------
logging:
  level:
    #  root: debug
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

#--------------------------
# actuator
#--------------------------
management:
  endpoints:
    enabled-by-default: false # 1. Endpoint all disable
    # 3. Exclude all endpoint for JMX and Expose specific endpoints
    web.exposure.include: "health,info"
    jmx.exposure.exclude: "*"
  # 2. Enable specific endpoints
  endpoint:
    info.enabled: true
    health:
      enabled: true
      probes.enabled: true
      defaults.enabled: true

#--------------------------
# jwt secret
#--------------------------
jwt:
  secret: 1e47d80ac0698f4cf303c6e7ba9a64a07767a21cb3674336489a7d96dee4762ee11e6827a04fa4c172174e88063f085f1d3c9370ead4f3aab44d30b31ea7bd05

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.hanex.auth
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: auth-service.html            # Swagger UI 경로 => localhost:8000/auth-service.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
