###################
# dev
###################
spring:
  datasource:
    #url: jdbc:postgresql://host.docker.internal:5432/hanexdb?currentSchema=sc_starter
    url: jdbc:postgresql://host.docker.internal:5432/hanexdb
    driverClassName: org.postgresql.Driver
    username: hanex
    password: hanex1234
  redis:
    host: host.docker.internal
    port: 6001

logging:
  config: classpath:log4j2-dev.xml

